a=int(input("enter the number:--"))
b=int(input("enter the number:--"))
print("the numbers are:-",a,b)
print("addition of given two number is::",(a+b))
print("subtraction of given two number is::",(a-b))
print("numtiplication of given two number is::",(a*b))
print("division of given two number is::",(a/b))
print("=================================================")